[package]
name = "vampire"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
overflow-checks = true
lto = true
debug = false
debug-assertions = false
incremental = false
panic = "unwind"

[dependencies]
configparser = "3.0.2"
